name: Tag master and create a release when there is a merge

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: tag main
        id: tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.tag.outputs.changelog }}
          tag: ${{ steps.tag.outputs.new_tag }}
